---
- name: Create the directories for site specific configurations
  become: yes
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
    owner: "{{ nginx_conf_user }}"
    group: "{{ nginx_conf_group }}"
    mode: "{{ nginx_dir_perm }}"
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "auth_basic"
    - "conf.d"
    - "conf.d/stream"
    - "snippets"
    - "modules-available"
    - "modules-enabled"
  when: ansible_connection != 'local'

- name: Create the directories for site specific configurations locally
  become: yes
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
    mode: "{{ nginx_dir_perm }}"
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "auth_basic"
    - "conf.d"
    - "conf.d/stream"
    - "snippets"
    - "modules-available"
    - "modules-enabled"
  when: ansible_connection == 'local'

- name: Ensure log directory exist
  become: yes
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: "{{ nginx_log_user }}"
    group: "{{ nginx_log_group }}"
    mode: "{{ nginx_log_perm }}"
  when: ansible_connection != 'local'
