---
- name: Disable the default site
  become: yes
  file:
    path: "{{ nginx_conf_dir }}/sites-enabled/default"
    state: absent
  notify:
    - reload nginx

- name: Disable the default site (on newer nginx versions)
  become: yes
  file:
    path: "{{ nginx_conf_dir }}/sites-enabled/default.conf"
    state: absent
  notify:
    - reload nginx
  when: >
     'default' not in nginx_sites.keys()

- name: Remove the default configuration
  become: yes
  file:
    path: "{{ nginx_conf_dir }}/conf.d/default.conf"
    state: absent
  when: >
    'default' not in nginx_configs.keys()
  notify:
    - reload nginx
