---
galaxy_info:
  author: Stan Bogatkin
  description: Ansible role to install Nginx.
  company: Personal project
  license: BSD
  min_ansible_version: 2.4
  role_name: nginx
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: FreeBSD
      versions:
        - 10.0
        - 10.1
        - 10.2
        - 10.3
        - 11.0
        - 11.1
    - name: SmartOS
  galaxy_tags:
    - web
    - nginx
allow_duplicates: yes
dependencies: []
