pipeline {
  agent any

  environment  {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }
  stages {
    stage('Initial cleanup') {
      steps {
        dir("${WORKSPACE}") {
          deleteDir() 
        }
      }
    }
    stage('Checkout SCM') {
       steps {
            git branch: 'main', url: 'https://github.com/Kachi79/NEW-ANSIBLE.git'
         }
       }
    stage('prepare Ansible for Execution') {
       steps {
             sh 'echo ${WORKSPACE}'
             sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
         }
       }
    stage('Run Ansible playbook') {
       steps {
        ansiblePlaybook colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'   
         }
       }
    stage('Clean workspace after build'){
       steps{
        cleanWs(cleanwhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
       }  