---
# tasks file for sonarqube
- name: set max_map
  become: true
  command: sysctl -w vm.max_map_count=262144

- name: set file max
  become: true
  command: sysctl -w fs.file-max=65536

 
- name: Add max limits
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: 
      - sonarqube   -   nofile   65536
      - sonarqube   -   nproc    4096
    create: yes


- name: Add ppa  repository 
  ansible.builtin.apt_repository:
    repo: ppa:linuxuprising/java


- name: install python3
  ansible.builtin.apt:
    name: 
      - python3
      - python3-pip
      - python3-dev
      - libpq-dev
    state: present

- name: Install setuptools
  pip:
    name: setuptools
    extra_args: --upgrade

- name: upgrade pip command
  pip:
    name: pip
    extra_args: --upgrade


- name: install pip dependencies
  pip:
    name:  psycopg2
    executable: pip3

- name: install java 11
  ansible.builtin.apt:
    name: 
      - openjdk-11-jdk
      - openjdk-11-jre
    state: present
    allow_unauthenticated: yes


- import_tasks: postgresql.yml

- name: Ensure group sonar exists
  ansible.builtin.group:
    name: sonar
    state: present

- import_tasks: sonarqube-setup.yml

- name: start and enable sonarqube
  ansible.builtin.service:
    name: sonar
    state: started
    enabled: yes