---
- hosts: db
- name: database assignment
  ansible.builtin.import_playbook: ../static-assignment/database.yml

- hosts: nginx
- name: nginx assignment
  ansible.builtin.import_playbook: ../static-assignment/nginx.yml

