---
# - hosts: all
# - import_playbook: ../static-assignments/common.yml

# - hosts: all 
# - import_playbook: ../static-assignments/common-del.yml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml
